/**
 * The share card: one description of it, for the two places that need it.
 *
 * The image itself is generated by the file-based route
 * `app/[locale]/opengraph-image.tsx`, which is the right way to do it — Next
 * builds the route, hashes it for cache-busting and injects the `og:image`
 * tags automatically. That injection has one limit that is easy to walk into,
 * and this file exists because of it.
 *
 * Next merges file-based image metadata into whatever `openGraph` object the
 * *same* route segment produced (`mergeStaticMetadata` in
 * `next/dist/lib/metadata/resolve-metadata.js`). The image file sits at the
 * `[locale]` segment, so it is merged into the layout's `openGraph`. When a
 * page one level down defines its own `openGraph`, that object *replaces* the
 * layout's — images and all — and by then the static merge for the page's own
 * segment has nothing to contribute, because there is no image file in the
 * page's directory. The share card silently disappears. It takes `twitter:image`
 * with it, since Next auto-fills the Twitter images from the Open Graph ones.
 *
 * Every page has to set `openGraph.url` (that is the whole point of
 * `pageMetadata`), so every page has to restate the image too. Restating it
 * from here rather than from a literal keeps the alt text and the dimensions
 * on one definition, which matters because the alt text is user-visible and
 * the dimensions have to match what the route actually renders.
 *
 * The one thing that is *not* reproduced is the build hash Next appends to the
 * generated URL (`…/opengraph-image?412646f928b3e21f`). It is a cache-busting
 * query and nothing reads it, so its absence costs a slower refresh of the
 * scrapers' caches when the card design changes, and nothing else.
 */

import { BASE } from '@/lib/hreflang';

export const OG_IMAGE_ALT = 'Agentic Mindshift — AI advisory for PE & M&A';
export const OG_IMAGE_SIZE = { width: 1200, height: 630 };
export const OG_IMAGE_CONTENT_TYPE = 'image/png';

/** The share card for one locale, as an Open Graph image descriptor. */
export function getOgImage(locale: string) {
  return {
    url: `${BASE}/${locale}/opengraph-image`,
    width: OG_IMAGE_SIZE.width,
    height: OG_IMAGE_SIZE.height,
    alt: OG_IMAGE_ALT,
    type: OG_IMAGE_CONTENT_TYPE,
  };
}
